# Site settings
permalink: /blog/:year/:month/:day/:title.html
title: Stetho
tagline: A debug bridge for Android applications
fbappid: "1615782811974223"
gacode: "UA-44373548-5"
description: > # this means to ignore newlines until "baseurl:"
  Stetho is a sophisticated debug bridge for Android applications. When enabled, developers have access to the Chrome Developer Tools feature natively part of the Chrome desktop browser. Developers can also choose to enable the optional dumpapp tool which offers a powerful command-line interface to application internals. 
baseurl: "/stetho" # the subpath of your site, e.g. /blog/
url: "https://facebook.github.io" # the base hostname & protocol for your site
ghrepo: "facebook/stetho"

# Build settings
markdown: redcarpet
highlighter: pygments

sass:
  style: :compressed
  
redcarpet:
  extensions: [with_toc_data]  
  
color:
  primary: "#46a24a"
  secondary: "#fff"
  light: "#66d16b"
  lighttext: "#fff"
  headertext: "#fff"
  bodytext: "#1d1d1d"
  nav: "#3d9941"
  navtext: "#95d998"
  link: "#46a44a"